#certoraRun.py certora/confs/StrategyManager_sanity_with_all_default_summaries.conf
#certoraRun.py certora/confs/StrategyManager_sanity_with_erc20dispatched.conf
#certoraRun.py certora/confs/StrategyManager_sanity_with_erc20cvl.conf
#certoraRun.py certora/confs/StrategyManager_sanity.conf
certoraRun.py certora/confs/StrategyManager_builtin_assertions.conf