# Global root confirmation threshold in basis points (e.g., 10000 = 100%)
globalRootConfirmationThreshold = 10000

# Reference timestamp
referenceTimestamp = 0

# Global root confirmer set configuration
[globalRootConfirmerSet]
avs = "0x0000000000000000000000000000000000000000"
id = 0

# Global root confirmer set config
[globalRootConfirmerSetConfig]
maxStalenessPeriod = 0
owner = "0x0000000000000000000000000000000000000000"

# Global root confirmer set info
[globalRootConfirmerSetInfo]
numOperators = 0
operatorInfoTreeRoot = "0x0000000000000000000000000000000000000000000000000000000000000001"
totalWeights = []
[globalRootConfirmerSetInfo.aggregatePubkey]
X = "0"
Y = "0"
