name: Check

on:
  push:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

env:
  CLICOLOR: 1

jobs:
  typos:
    name: Typo Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.29.7
        with:
          config: .github/configs/typos-cli.toml

  go-bindings:
    name: Bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and validate
        if: github.event_name == 'push'
        run: |
          make docker
          docker run -v `pwd`:/build -w /build --rm -i eigenlayer-contracts:latest bash -c "make gha"
          if [ ! -z "$(git status --porcelain)" ]; then git diff; git status; exit 1; fi