name: Check

on:
  push:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

env:
  CLICOLOR: 1

jobs:
  typos:
    name: Typo Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.29.7
        with:
          config: .github/configs/typos-cli.toml

  commitlint:
    name: Commit Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6

  go-bindings:
    name: Bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and validate
        if: github.event_name == 'push'
        run: |
          make docker
          docker run -v `pwd`:/build -w /build --rm -i eigenlayer-contracts:latest bash -c "make gha"
          if [ ! -z "$(git status --porcelain)" ]; then git diff; git status; exit 1; fi
  
  labels:
    name: Labels
    # Only run on pull requests that don't have any labels
    if: github.event_name == 'pull_request' && github.event.pull_request.labels[0] == null
    runs-on: ubuntu-latest
    steps:
      - name: Fail if this PR has no labels
        run: |
          echo "This PR has no labels. Please add the appropriate labels to the PR."
          exit 1