name: Check

on:
  push:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

env:
  CLICOLOR: 1

jobs:
  natspec:
    name: Natspec Linting
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            release-assets.githubusercontent.com:443
            objects.githubusercontent.com:443
            raw.githubusercontent.com:443
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Run Natspec Lint
        uses: beeb/lintspec@fd5b71ffc838f63f81caf3e85e90760d124efac2 # v0.4.1
        with:
          working-directory: "./"
          paths: "[./src/contracts/]" # Only lint src/contracts/
          exclude: "[]"
          extra-args: "" # TODO: Config
          version: "latest"
          fail-on-problem: "true"

  typos:
    name: Typo Linting
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            release-assets.githubusercontent.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: crate-ci/typos@717cd03663352cbd05e4d28c01366e571ff5f2ed
        with:
          config: .github/configs/typos-cli.toml

  go-bindings:
    name: Bindings
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: block
          allowed-endpoints: >
            archive.ubuntu.com:80
            auth.docker.io:443
            binaries.soliditylang.org:443
            foundry.paradigm.xyz:443
            gethstore.blob.core.windows.net:443
            github.com:443
            production.cloudflare.docker.com:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            release-assets.githubusercontent.com:443
            security.ubuntu.com:80
            objects.githubusercontent.com:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Build and validate
        if: github.event_name == 'push'
        run: |
          make docker
          docker run -v `pwd`:/build -w /build --rm -i eigenlayer-contracts:latest bash -c "make gha"
          if [ ! -z "$(git status --porcelain)" ]; then git diff; git status; exit 1; fi
