name: Check

on:
  push:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

env:
  CLICOLOR: 1

jobs:
  typos:
    name: Typo Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typos CLI (Latest)
        run: |
          TYTOS_VERSION=$(curl -s https://api.github.com/repos/crate-ci/typos/releases/latest | jq -r .tag_name)
          curl -Ls https://github.com/crate-ci/typos/releases/download/${TYTOS_VERSION}/typos-${TYTOS_VERSION}-x86_64-unknown-linux-musl.tar.gz | tar xz
          sudo mv typos /usr/local/bin/

      - name: Run typos check
        run:  typos --config .github/configs/typos-cli.toml

  commitlint:
    name: Commit Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6

  go-bindings:
    name: Bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and validate
        if: github.event_name == 'push'
        run: |
          make docker
          docker run -v `pwd`:/build -w /build --rm -i eigenlayer-contracts:latest bash -c "make gha"
          if [ ! -z "$(git status --porcelain)" ]; then git diff; git status; exit 1; fi