name: Lint and Check Format
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "dev"
jobs:
  check:
    strategy:
      fail-fast: true
    name: Foundry Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run forge fmt for src/contracts
        run: |
          forge fmt --check
        id: fmt_contracts
      - name: Run forge fmt for script and src/test
        run: |
          FOUNDRY_PROFILE=test forge fmt --check
        id: fmt_script_test
      - name: Install npm dependencies
        run: npm install --include=dev
      - name: Run solhint
        run: npm run hint
