name: Lint and Check Format
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "dev"
jobs:
  check:
    strategy:
      fail-fast: true
    name: Foundry Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run forge fmt
        run: |
          forge fmt --check src/contracts
        id: fmt
      - name: install npm dependencies
        run: npm install --include=dev
      - name: run solhint
        run: npm run hint