name: Foundry

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

# Add explicit permissions
permissions:
  contents: read
  pull-requests: read

env:
  FOUNDRY_PROFILE: medium

jobs:
  # -----------------------------------------------------------------------
  # Forge Test
  # -----------------------------------------------------------------------

  test-suite:
    name: Test
    runs-on: protocol-x64-16core
    # Add this to make sure the job runs for fork PRs
    if: ${{ github.event_name != 'pull_request_target' || github.event.pull_request.head.repo.full_name != github.repository }}
    strategy:
      matrix:
        suite: [Fork]
    
    steps:
      # Add debugging information
      - name: Debug Event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "PR head repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Base repo: ${{ github.repository }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "SHA: ${{ github.event.pull_request.head.sha }}"

      # Check out repository with all submodules for complete codebase access.
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          # This ensures we check out the PR's code, not the base branch
          ref: ${{ github.event.pull_request.head.sha }}
          # Add fetch-depth to ensure we get all history
          fetch-depth: 0

      # Restore Forge cache
      - name: Cache Forge Build
        uses: actions/cache@v3
        with:
          path: |
            cache/
            out/
          key: ${{ runner.os }}-forge-${{ hashFiles('**/foundry.toml', '**/remappings.txt', 'src/**/*.sol', 'lib/**/*.sol') }}
          restore-keys: |
            ${{ runner.os }}-forge-

      # Install the Foundry toolchain.
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      # Run Forge's formatting checker to ensure consistent code style.
      - name: "Forge Fmt"
        run: |
          forge fmt --check
          FOUNDRY_PROFILE=test forge fmt --check
        id: fmt

      # Build the project and display contract sizes.
      - name: Forge Build
        run: |
          forge --version
          forge build --sizes

      # Run the test suite in parallel based on the matrix configuration.
      - name: Run ${{ matrix.suite }} tests
        run: |
          case "${{ matrix.suite }}" in
            Fork) forge test --match-contract Integration --fork-url "${{ secrets.RPC_MAINNET }}" ;;
          esac
        env:
          FOUNDRY_PROFILE: ${{ matrix.suite == 'Fork' && 'forktest' || 'medium' }}
