name: Storage Diff

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "dev"

jobs:
  storage-diff:
    name: CI

    # Use latest Ubuntu runner.
    runs-on: ubuntu-latest

    steps:
      # Check out repository with all submodules for complete codebase access.
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install the Foundry toolchain.
      - name: "Install Foundry"
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      # Run storage diff check to detect storage layout incompatibilities.
      - name: "Storage Layout Check"
        run: |
          bash bin/storage-diff.sh --rpc-url ${{ secrets.RPC_MAINNET }} --etherscan-key ${{ secrets.ETHERSCAN_API_KEY }} --input .github//storage-diff.json
        id: storage-diff
